### PR TITLE
Added support for CSS files; fixed bug in urldecode function

### PR DESCRIPTION
**Pull request by jduga002**

### CODE REVIEW

**Comment by mikeizbicki** [comment]
Why do we need to do an explicit check for css file when we didn't need an explicit check for html files?

**Comment by jduga002** [comment]
I added this check because it wasn't correctly identifying the mime-type of my css file; it was saying it was `text/plain` rather than `text/css`. However, it works correctly for my `index.html` file.

**Comment by mikeizbicki** [comment]
In that case, it would be better to make the if statement just surround the section of code related to getting mime-types for static files.  Does that make sense?  You should also add a comment explaining why the if statement needs to be there.

**Comment by jduga002** [comment]
Alright, working on it now.

**Pull request closed without merging**
